### PR TITLE
Fix dependency conflict issues #8, #9

### PR DESCRIPTION
**Pull request by HelloCoCooo**
Fix dependency conflict issue for com.fasterxml.jackson.core:jackson-databind #8 
Fix dependency conflict issue for com.fasterxml.jackson.core:jackson-core #9

### CODE REVIEW

**Review by buremba — APPROVED** [review]

**Comment by buremba** [comment]
Thanks!

**Comment by HelloCoCooo** [comment]
@buremba 
By the way, have you ever encountered these types of semantic behavior inconsistency issues (the methods with the same signatures but different implementations) when upgrading libraries or dealing with dependency conflict issues?

How did you discover such inconsistency issues? (by testing, code review, user feedback, static analysis tool, inquiring in forum (e.g., stackoverflow) or in other ways?)

Thanks a lot!
Coco

**Comment by buremba** [comment]
@HelloCoCooo maven-dependency-plugin helps in this case if you're using Maven. It detects (almost) all inconsistency issues regarding the dependencies that you're using and doesn't let Maven build the project without solving these issues. See here: https://maven.apache.org/plugins/maven-dependency-plugin/plugin-info.html

**Comment by HelloCoCooo** [comment]
@buremba Thank you for your reply.
What do your inconsistency issues refer to?
Which 'goal' of this plugin in the 'Plugin Documentation' can deal with the semantic behavior inconsistency issues at method level?  Especially for the methods with the same signatures but different implementations.

**Comment by buremba** [comment]
1. Please take a look at the link that I shared, it has much more information that I'm aware of.
2. `analyze-only`, `analyze-duplicate` and `analyze-dep-mgt`. 
In fact, there is no easy way to detect `the same signatures but different implementations`, this plugin analyzes all the dependencies and detects the version mismatches. If there are 2 different versions of the same dependency at runtime, it won't allow you to build the project unless you exclude one of them so it makes you aware of the inconsistency issues early on.
Then, you need to take a look at the changelog of the dependency and find out if these 2 versions are compatible with each other. I do not think that there is a convenient way to check if they have `different implementations` because the only way is to analyze the bytecode and even that wouldn't be convenient because different bytecode doesn't imply different implementation.

What's the exact issue that you run into?

**Pull request merged**
